services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/cfdaas
    depends_on:
      - mongo
    command: npm run start:debug

  mongo:
    image: mongo:8.0-noble
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data:
